Code Review Preparation Milestone 3, Tic-Tac-Toe
Emmanuelaaron/tic-tak-toe pull request #4
Opened 2020-05-14 22:36 UTC by jamezjaz

This is a Tic-Tac-Toe game!
On this branch we did the following:
- Added game logic 
- Got rid of inline comments
- Encapsulated some game parts of the game logic in classes

2020-05-15 14:25 UTC, majovanilla requested changes
Hey team, 👋

## You did a *great* job on this project! 💜 

There are still some changes 👇 you need to implement to approve this request 🔍 I left the comments on your code.

The main thing is that you are not organizing your methods in the proper way, You need to create different files for each class in the `lib` folder and move everything (logic) there and leave only the `puts` and `chomp` on your `main.rb `file.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-05-15 14:25 UTC, majovanilla commented on bin/main
> +  def initialize(board, current_player)
All classes are kept in the lib directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from Pathwright) This is the way you should organize every Ruby project from now on.

Keep each class in a different file inside your lib folder to improve your project's organization.

In your` main.rb` you should only have the necessary code to start the game and the `puts` and `chomp`

2020-05-15 14:25 UTC, majovanilla commented on bin/main
> +    @player2 = gets.chomp
You should improve this part. Right now, I can leave the name blank for both players and that makes your game's interface very confusing when talking turns since you can't know which players' turn is.

Consider validating the name to avoid duplicates, too.

Also, remember that once you move your code, this can't be on your lib folder because it has `puts` and `chomp`.

2020-05-15 14:25 UTC, majovanilla commented on bin/main
> +    puts @board[6] + '|' + @board[7] + '|' + @board[8]
Your board is displaying just the design but then you ask your player's to choose a number from 1-9. You should display those numbers on the board so that they can see what the available cell is (yeah, in the remote case that they have never played this game before!) It's more user friendly.

When you move this class you won't be able to use `puts`, I suggest you return the string on your method and then `puts` it on `main.rb`

2020-05-15 14:25 UTC, majovanilla commented on bin/main
> +    @current_player = current_player
Keep in mind that you only need `instance` variables when you are accessing your variable from **outside** the class. Keep this in mind when you re-arrange your code.

2020-05-15 14:25 UTC, majovanilla commented on bin/main
> +        puts "#{player1} wins"
Since you can't have `puts` on your class methods on lib, you are going to need to remove this and puts it from the` main.rb` file.

In here it is useful to have the players' names as instance variables so you can access them and avoid the need to pass them as parameters (as you have in other methods)

2020-05-15 14:25 UTC, majovanilla commented on bin/main
>      end
You will have to modify this method, too. I suggest you leave the `until arr.include?` part and call it in main.rb with the player's choice as an argument.

2020-05-15 14:25 UTC, majovanilla commented on bin/main
>      end
You are going to have to move this too. Maybe separate it into a different method to keep things organized.

2020-05-15 14:25 UTC, majovanilla commented on bin/main
> +    @game_on_going = false if validate.validate_wins(2, 4, 6, @Player2, @player1)
did you try with `||` instead of assigning the variable multiple times??
If you improve your validate method, this could get a lot easier.

2020-05-15 14:25 UTC, majovanilla commented on bin/main
> +  end
After you re-arrange your code, remember to remove the `puts` from here.

2020-05-16 09:58 UTC, suretrust requested changes
Hi team, 👋 

### Great job implementing some of the suggested changes. 🙌 However, there is one you are yet to fix. 👇 
* [ ] All classes should be in the `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

**Kindly fix this and submit for another CRR.** _Happy coding!_ 🎉

2020-05-19 23:29 UTC, mikenath223 requested changes
### Hi Team 👋

You've done quite well on this. This looks quite ok @jamezjaz  and @Emmanuelaaron 
However, let's fix the following issues to make it even more awesome🚀

- [ ] On inputting player names, it's noticed that blank names are allowed, and this shouldn't be, perhaps you can check the names that are inputted and avoided blank inputs, or duplicate names, kindly fix this.

- [ ]  Also it can be observed that if my last move is a winning move, the game outputs that it's a tie, as well as output that it is also a draw, perhaps you can try checking for winning moves before you check for ties.[Screenshot]👇
![ice_screenshot_20200519-192834](https://user-images.githubusercontent.com/33323077/82387955-3bc38b00-9a30-11ea-9409-3f03bdce94ca.png)

- [ ] In addition, it would be nice to see the numbers on each board, it's more user-friendly that way, so users won't have to keep guessing which number belongs to a board position. Right now your board only has dashes for empty position, kindly replace it with numbers. [Screenshot]👇
![ice_screenshot_20200519-192540](https://user-images.githubusercontent.com/33323077/82388082-93fa8d00-9a30-11ea-9327-47bd9e1bb89b.png)

Once again you guys have done really well on this, just fix these issues and request another review and we are good to go. 👍👍

Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-05-21 01:02 UTC, mikenath223 approved these changes
### CONGRATULATIONS  Team 👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

2020-05-21 01:04 UTC, merged